### ISSUE TITLE
Crash when breeding cows

### ISSUE THREAD

**Issue by slard3** [SaemonMoki/ExtendedAnimals#10]
https://hastebin.com/ikopojivod.pl

My only mod that has anything about breeding (I don't know if it's relevant):
https://www.curseforge.com/minecraft/mc-mods/pet-names

**Comment by SaemonMoki** [comment]
I had a look at this.
Unfortunately I don't think this is something either us, or pet-names can fix. Pet names will, on breeding, name the baby.
However our mod does not make the baby when they are bred. Instead it will start a pregnancy timer and then after that time the baby will appear.

As pet-names expects a baby at the time they are bred, it throws an error for our entities.
There is unfortunately nothing we can do to fix this in particular. Unless we just entirely remove the pregnancy functionality.

**Comment by slard3** [comment]
Oh, I understand. Thank you 👍
