### ISSUE TITLE
1.14.4-0.4.9 crashes dedicated server Forge 1.14.4 build 28.1.39

### ISSUE THREAD

**Issue by kreezxil** [SaemonMoki/ExtendedAnimals#11]
Notes:
     failed to load registries

crash report:
http://paste.ubuntu.com/p/BN6Yy8QDcp/

fml server latest:
http://paste.ubuntu.com/p/mVcnRRfkT6/

**Comment by SaemonMoki** [comment]
This is minecraft servers unable to load normal minecraft client gui classes. I'll just remove the gui work until we can find an alternative.

**Comment by SaemonMoki** [comment]
Latest version fixes this
