### ISSUE TITLE
[1.14.4] Sidedness issue with Genetic Animals 0.4.10 on a dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [SaemonMoki/ExtendedAnimals#12]
https://gist.github.com/ProsperCraft/a49121548b61dd93adcab387d8d0a519

[latest.log](https://github.com/SaemonMoki/ExtendedAnimals/files/3703149/latest.log)
[debug.log](https://github.com/SaemonMoki/ExtendedAnimals/files/3703150/debug.log)

**Comment by ProsperCraft** [comment]
And 4.9

**Comment by SaemonMoki** [comment]
Fixed as of 0.4.11 👍
