### ISSUE TITLE
0.4.10 crashes dedicated server Forge 1.14.4 build 28.1.40

### ISSUE THREAD

**Issue by kreezxil** [SaemonMoki/ExtendedAnimals#13]
Notes:
     LoadingFailedException, rolling back to 0.4.8 to resolve it

crash report:
http://paste.ubuntu.com/p/dcysC4J8XG/

fml server latest:
http://paste.ubuntu.com/p/zhPzRJHZ99/

this appears to be same as #11

**Comment by ProsperCraft** [comment]
Scroll up Kreez...its a sidedness issue
Line 83
Attempted to load class net/minecraft/client/gui/screen/Screen for invalid dist DEDICATED_SERVER

Trying to load a gui on a dedicated server will always get you in trouble :)

https://github.com/SaemonMoki/ExtendedAnimals/issues/12

Unfortunately, Forge doesn't pull the right stacktraces and you often have to scroll up to see the real problem.

Can close this one while waiting for 12 to get fixed.

**Comment by SaemonMoki** [comment]
Fixed as of 0.4.11 👍

**Comment by kreezxil** [comment]
would it be possible to change the repository name to match the name on
Curseforge, I get confused everytime I see "Extended Animals". the
curseforge page says "genetic animals"
