### ISSUE TITLE
[1.14.4] Server deadlock mokiyoki.enhancedanimals.entity.EnhancedCow.onLivingUpdate()100.00%

### ISSUE THREAD

**Issue by ProsperCraft** [SaemonMoki/ExtendedAnimals#14]
Warmroast profile while the server is locked hard-

![83f0b966d1fbcf132f89ece8e84db255](https://user-images.githubusercontent.com/4427684/66532194-b526f280-eacb-11e9-8af7-6b20f47414e5.png)

GeneticAnimals_0_4_8

mokiyoki.enhancedanimals.entity.EnhancedCow.onLivingUpdate()100.00%

**Comment by ProsperCraft** [comment]
[lock.zip](https://github.com/SaemonMoki/ExtendedAnimals/files/3710069/lock.zip)

Here are the server logs.

**Comment by ProsperCraft** [comment]
Here is another one that happened right after I rebooted and players started logging in.

![69638e89f85616180ebc46a467db8626](https://user-images.githubusercontent.com/4427684/66532843-0fc14e00-eace-11e9-8411-20ffee496345.png)

**Comment by ProsperCraft** [comment]
May have cornered it - after removing solcarrot, and Genetic Animals

https://github.com/TeamLapen/Vampirism/issues/538

**Comment by SaemonMoki** [comment]
I have attempted to reproduce this issue, however I have not been able to with the provided mods. From my examinations it appears 'something' is grabbing a lock on an entire chunk. Then upon entity spawn it is locked waiting for the chunk information to be released.

To my knowledge, this only occurs if any mods are attaching capabilities during chunk gen and do *not* use the IWorld object for world calls. I doubt checked we are doing the right calls and can confirm it is not something we do.

If you are still experiencing this issue, if you could explain the steps to reproduce, I can try to see if I can get my own local server to lock up in the same way.

**Comment by ProsperCraft** [comment]
This was most likely caused by this - https://github.com/TeamLapen/Vampirism/issues/538#issuecomment-540477150
