### ISSUE TITLE
0.4.7: Cannot access config

### ISSUE THREAD

**Issue by Oddlybird** [SaemonMoki/ExtendedAnimals#15]
I'm using Forge for minecraft 1.14.4, and when I go to the mods tab, the "config" button for eanimals 0.4.7 is greyed out.  I've tried poking around inside the .jar, but didn't find any easy way to access config from there either.

Advice?

**Comment by SaemonMoki** [comment]
type %appdata% in your file explorer, click .minecraft , click config, click eanimod-common. Thats the config file. Hope that helps but this is not a bug :) Use Discord, the minecraft forums or the mod page for questions next time.
