### ISSUE TITLE
bad recipes for posts

### ISSUE THREAD

**Issue by kreezxil** [SaemonMoki/ExtendedAnimals#16]
please disable the recipe that produces posts when slabs go horizontal as that conflicts with recipes that try to produce drying racks.

![image](https://user-images.githubusercontent.com/3880072/68547922-2ef11b00-03ad-11ea-9568-a989320e04a9.png)

**Comment by KingOfTheGamesYT** [comment]
I'm having this issue as well because the horizontal recipe conflicts with the recipe for drying racks from Silents Mechanisms.

**Comment by kreezxil** [comment]
@KingOfTheGamesYT I created a mod that resolves this by converting posts to racks in a recipe system. 

https://www.curseforge.com/minecraft/mc-mods/better-with-regime

**Comment by KingOfTheGamesYT** [comment]
I know you did :) I'm the owner of that pack.

**Comment by SaemonMoki** [comment]
changed in latest release
