### ISSUE TITLE
1.15.2 java.lang.IllegalStateException: No renderer registered for eanimod:enhanced_cat

### ISSUE THREAD

**Issue by SDUBZ** [SaemonMoki/ExtendedAnimals#35]
forge: 1.15.2-31.1.77
GA: GeneticAnimals-0_5_4
logs:
[latest.log](https://github.com/SaemonMoki/ExtendedAnimals/files/4608278/latest.log)

**Comment by SaemonMoki** [comment]
there is not cats yet, ignore the error
