### ISSUE TITLE
Took too long to log in

### ISSUE THREAD

**Issue by Mingu2209** [SaemonMoki/ExtendedAnimals#46]
Hi,

I tried your mod in server and I love it! I wanted to add it to my server and I can't log in. This messages appears in the console and in my client: "took too long to log int".

I would love to use it. I have many other mods and isolating yours i saw that your mod is causing the problem. Is there any way to fix it?

Forge version: 34.1.19
Genetic Animals version:GeneticAnimals-0_6_2.jar

I have 2 questions as well:

1) Is there any config option to keep the animals with vanilla's textures?
2) If I use your mod, all animals are with the config of your mod or there are others that spawn "normally"?

Thanks in advance for your help on this matter!

**Comment by Voknehzyr** [comment]
Expecting same problem here.

**Comment by SaemonMoki** [comment]
I'm going to need more details for this, server info, distance from server, logs ect ect. As I cannot reproduce it no matter what I do.

As for your questions:
1: No we cannot have vanilla textures, it would also entirely defeat the entire point of our mod which is breeding for traits that are often visible by the textures.
2: All are animals are controlled in our config file.

**Comment by No3371** [comment]
"Took too long to log in" is not exactly the symptom, that is just what Minecraft do when a player take too long when joining the world.

I have the same problem so I haven't isolate it down to which mods, but I'd not be surprised if all the `new` and string usage in the init code add a significant load time... (I don't code mods though, just saying with my C# experience)

**Comment by SaemonMoki** [comment]
Latest version addresses this.
