### ISSUE TITLE
Sheeps do not give wool

### ISSUE THREAD

**Issue by emanuele246gi** [SaemonMoki/ExtendedAnimals#50]
When I try to shear the sheeps, nothing happen, I don't know why

**Comment by SaemonMoki** [comment]
Sheep grow wool over time, sheering them when they have barely any has a much lower chance of dropping wool. We have made some tweaks to the latest versions that will be released shortly that make this a bit easier.

**Comment by emanuele246gi** [comment]
Thanks!
