### ISSUE TITLE
Quark Compatibility?

### ISSUE THREAD

**Issue by RandomMcSomethin** [SaemonMoki/ExtendedAnimals#51]
It would be nice if the animals in this mod were compatible with Quark.  For instance, chickens should periodically drop feathers and pigs should drop tallow.  Since they don't, I can't use those features without further intervention.

**Comment by SaemonMoki** [comment]
Not exactly _easy_ to do. Quark specifies minecraft:chicken as it's entity target, there isn't really anything I can hook into to work with that. I would have to specifically organise custom code in Quark with the maker of Quark.
