### ISSUE TITLE
Animals won't breed?

### ISSUE THREAD

**Issue by Chaicilius** [SaemonMoki/ExtendedAnimals#52]
I've made a pen in my world with about 10 sheep. I know that genders can be assigned and I admit I don't know if that's turned on or not, but I've tried many, many combination of breeding pairs and they won't breed? I don't understand why, whether I'm being dumb or if it's a bug?

**Comment by SaemonMoki** [comment]
Our mod has Pregnancies, so the animals will be pregnant for a time before giving birth. Not instantly like in regular minecraft.
