### ISSUE TITLE
Sideways pig

### ISSUE THREAD

**Issue by Smile1ash1** [SaemonMoki/ExtendedAnimals#53]
I loaded a world in 1.16.4 and 2 genetic pigs spawned laying on their side, this continued after I hit one and it chased me on land and in water. This is my third mod, I have doggy talents and ultimate unicorns installed also. A couple of chickens also spawned and they seem a bit long and inactive but maybe that's just how they are.

**Comment by Smile1ash1** [comment]
Edit this did happen at night, do animals sleep? sideways chase is still a bit weird though. the second pig is walking around as well as the chickens
s

**Comment by SaemonMoki** [comment]
Animals sleep yes. The bug of them following you while asleep will be fixed in the upcoming version.
