### ISSUE TITLE
[1.16.4] Exception ticking world

### ISSUE THREAD

**Issue by ocram9** [SaemonMoki/ExtendedAnimals#54]
The server crashes after a while of playing, the crash log points to a wandering trader and this mod. 

- Forge 31.1.28
- Minecraft 1.16.4
- Genetic Animals 0.6.5

Log: https://gist.github.com/ocram9/30232cab154bb9d98b2848a2cc650114

**Comment by SaemonMoki** [comment]
Haven't been able to reproduce this no matter what I do. With a modlist as massive as yours, it will take a long time to track down what might be interfering with this.

**Comment by ocram9** [comment]
Yeah that's fair, this only happened once so I'll just assume it's a one off and close this issue.
