### ISSUE TITLE
Leatherworker caused crash [log with list of mods included]

### ISSUE THREAD

**Issue by tylerius** [SaemonMoki/ExtendedAnimals#56]
Hello, I experienced a crash with my modded 1.16 game. Around 100 mods. Its actually vivecraft (which uses Forge 35.0.7) I looked at the crash log and traced it back to this mod. I looked at the other mods I have that may also deal with villagers but I'm kind of at a loss. Most of the mods are totally unrelated at least I think. I'm wondering what `mokiyoki.enhancedanimals.util.EanimodVillagerTrades.getEanimodTrade(EanimodVillagerTrades.java:103)` is and if there's any way, maybe through crafttweaker or something that I can disable something to make the conflicting mods (if that's the case) compatible.

[crash-2021-01-05_07.39.02-server.txt](https://github.com/SaemonMoki/ExtendedAnimals/files/5782568/crash-2021-01-05_07.39.02-server.txt)

**Comment by tylerius** [comment]
I see betterhurttimer in there so im going to try disabling that.

**Comment by SaemonMoki** [comment]
upcoming release fixes this
