### ISSUE TITLE
Sheep wool not rendering

### ISSUE THREAD

**Issue by ZoeyR** [SaemonMoki/ExtendedAnimals#61]
In the latest version there seems to be a bug with sheep wool. It stops rendering after a bit and the tail keeps getting further and further away.

![2020-12-28_21 21 24](https://user-images.githubusercontent.com/8010244/106268497-80442f00-622b-11eb-94e0-ba5ee30a91bb.png)

**Comment by SaemonMoki** [comment]
If you join our discord, there is a pre-release version that fixes this. Otherwise the upcoming version will address it.
