### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by iobiarg** [SaemonMoki/ExtendedAnimals#62]
Hi there! Really loving your mod so far, it makes me remember just a bit of one I used to play in 1.12. 
My suggestion: More byproducts: milk from cows, sheep and goat, cheese/butter from this. Probably you could come up with sth more original.
It's just an idea, but I'm really into the mod. Congratulations!

**Comment by SaemonMoki** [comment]
We have intentions for such products, as it is a good way to demonstrate the differences in genetics. However we want to do something more creative rather than just adding more items.
We do have milk from cows and sheep currently.
