### ISSUE TITLE
Animals not breeding(1.16.4)

### ISSUE THREAD

**Issue by C4nte1r0** [SaemonMoki/ExtendedAnimals#64]
I've tried to breed cows and sheep when playing survival but they don't seem to breed

**Comment by SaemonMoki** [comment]
Our mod adds pregnancy, when you breed animals together they will take time before giving birth, usually a few minecraft days.

**Comment by C4nte1r0** [comment]
Yh I know ,  I waited  10 mimecraft days  and  it  didn't  work

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
