### ISSUE TITLE
Rendering entity in world crash

### ISSUE THREAD

**Issue by benurecarmin** [SaemonMoki/ExtendedAnimals#65]
Hello,

My game random crash with an error about chicken rendering (I think).
The crash report is in attachment
I don't know if you need other information  so tell me if you need^^'

[crash-2021-02-28_16.55.35-client.txt](https://github.com/SaemonMoki/ExtendedAnimals/files/6057070/crash-2021-02-28_16.55.35-client.txt)

**Comment by SaemonMoki** [comment]
We fixed this bug in 0.6.23+ 
Thanks
