### ISSUE TITLE
Shaders renders mobs semi transparent

### ISSUE THREAD

**Issue by Zyachim** [SaemonMoki/ExtendedAnimals#67]
This is more like a shaders problem than the mod itself, but I figured I'd post here anyways

![image](https://user-images.githubusercontent.com/77022572/114101577-e84e6b80-9893-11eb-91ca-2626af1a92d6.png)

Version: 0.6.29
Client: 1.16.5 (forge 36.1.0)
Optifine HD U G8 preview 11
Sildurs v1.283

**Comment by sekelsta** [comment]
I believe yesterday's update to Sildur's shaders should fix it, or if not, version 1.27 of the shader works

**Comment by SaemonMoki** [comment]
confirmed to work in later version of Sildur's Shaders
