### ISSUE TITLE
Animals with negative age on server

### ISSUE THREAD

**Issue by EllenMei02** [SaemonMoki/ExtendedAnimals#69]
![Capture](https://user-images.githubusercontent.com/82590125/114871409-41079200-9dc7-11eb-8b38-291f2ee730e2.PNG)

I know the simple answer is to just kill all the animals and spawn in new ones. but ive been working on my cows for a while and my friend has 50+ baby chickens now that he has also been working on.
I think this all happened because I tried to install a furniture mod on the server and when I removed it I came back to a bunch of baby animals that range form -1000 days to -100 days. Even animals in the wild are affected by this.

**Comment by SaemonMoki** [comment]
This.. is a little unusual. In future versions we might add checks to reset ages to start from 0 if they become negative from outside influences, but sadly that's the best fix I can offer.
