### ISSUE TITLE
Escaping village animals

### ISSUE THREAD

**Issue by InspectorCaracal** [SaemonMoki/ExtendedAnimals#78]
I encountered my first village animal pasture the other day and it looks great... except there was a hay block placed just inside the pasture, right up next to the fence. As a result, all of the animals that spawned in the pasture escaped almost immediately by jumping onto the hay bale and over the fence. They were out before I'd even gotten there; I thought there was a loading bug at first, and then I spotted the hay bale. >.>

I don't know how the new village structures are defined or how many there are, but in order to keep the village purebreds from escaping, the pasture(s) need an empty space between any hay bales and the fences - outside *and* inside, to keep other animals out, too.

p.s. This mod is coming along great! I'm enjoying it a lot.

**Comment by ElectricVersion** [comment]
Unfortunately this is out of the mod's scope, since we don't modify or add any village structures - just the animals that spawn in them
