### ISSUE TITLE
Chickens sleepwalking

### ISSUE THREAD

**Issue by InspectorCaracal** [SaemonMoki/ExtendedAnimals#80]
I went into my chicken pen while they were sleeping to collect some eggs and they immediately sleepwalked right out the gate past me.

It's only happened twice so far and only with Young Chickens, but I don't know if that's related. I'll post more info if it keeps happening.

**Comment by ElectricVersion** [comment]
Since the chicken AI has gotten a complete overhaul since this report and this no longer seems to be an issue, considering this fixed
