### ISSUE TITLE
Sleepwalking?

### ISSUE THREAD

**Issue by SKADE98** [SaemonMoki/ExtendedAnimals#82]
not sure if this counts as a bug but if a pig is agro and then night falls it stays in the "sleeping" pose while following you and dealing damage.... looks a pit weird gliding along the ground. not sure if it still happens in other situations (was already sleeping when provoked, etc) It will switch to the swimming animation when in water, though it lays on its side as soon as it gets out of the water.

**Comment by SaemonMoki** [comment]
This is fixed and we are releasing specifically a bug fix version containing it
