### ISSUE TITLE
Incorrect operation on the Linux server

### ISSUE THREAD

**Issue by ww1150** [SaemonMoki/ExtendedAnimals#91]
![image](https://user-images.githubusercontent.com/20845621/188269419-52320bf0-31bd-4e28-8c81-6549345b89c4.png)

**Comment by ww1150** [comment]
Configs were created in the root directory of the server

**Comment by ww1150** [comment]
Use "/" instead of "\" for the linux server

**Comment by SaemonMoki** [comment]
In the latest released version(for 1.17/1.18) this has been fixed
